In [1]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.full(7, 2.7)

array([2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(8, 20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.linspace(0,100, 12)

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [9]:
a = np.array([0,1,2,3,4,5, 6,7,8,9])

In [10]:
a[2]

2

In [11]:
a[3] = 12
a

array([ 0,  1,  2, 12,  4,  5,  6,  7,  8,  9])

### Multi dimension

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ab = np.array([
    [1,6,3],
    [0,4,1],
    [1,5,9]
])

In [14]:
ab[2]

array([1, 5, 9])

In [15]:
ab[1,2]

1

In [16]:
ab[:,2]

array([3, 1, 9])

In [17]:
ab[:,1] = [10,11,12]
ab

array([[ 1, 10,  3],
       [ 0, 11,  1],
       [ 1, 12,  9]])

In [18]:
np.random.rand(5,2)

array([[0.15706655, 0.06476365],
       [0.67862545, 0.4890275 ],
       [0.6237008 , 0.94189315],
       [0.35326772, 0.63002844],
       [0.50668353, 0.27418203]])

In [19]:
# Will produce same random
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:
a = np.array([1,6,8,2,4])
b = np.array([9,3,2,4,7])

In [22]:
a+b

array([10,  9, 10,  6, 11])

In [23]:
a > b

array([False,  True,  True, False, False])

In [24]:
a[a>b]

array([6, 8])

In [25]:
b[a>b]

array([3, 2])

In [26]:
a.min()

1

In [27]:
a.sum()

21

In [28]:
a.mean()

4.2

In [29]:
2*np.array([1,2])

array([2, 4])

### Linear algebra

#### Dot vection multiplication

In [30]:
a*b

array([ 9, 18, 16,  8, 28])

In [31]:
ab

array([[ 1, 10,  3],
       [ 0, 11,  1],
       [ 1, 12,  9]])

In [32]:
c = np.array([1,2,3])

In [33]:
c*ab

array([[ 1, 20,  9],
       [ 0, 22,  3],
       [ 1, 24, 27]])

In [34]:
ab.dot(c)

array([30, 25, 52])

In [35]:
c.dot(ab)

array([ 4, 68, 32])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.linalg.det(ab)

64.00000000000003

In [39]:
print(ab)
print(np.linalg.inv(ab) )

[[ 1 10  3]
 [ 0 11  1]
 [ 1 12  9]]
[[ 1.359375 -0.84375  -0.359375]
 [ 0.015625  0.09375  -0.015625]
 [-0.171875 -0.03125   0.171875]]


In [40]:
abi = np.linalg.inv(ab)
abi

array([[ 1.359375, -0.84375 , -0.359375],
       [ 0.015625,  0.09375 , -0.015625],
       [-0.171875, -0.03125 ,  0.171875]])

In [41]:
np.dot(ab,abi)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Pandas

### DataFrame

In [42]:
import pandas as pd

In [43]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [44]:
df0 = pd.DataFrame(data, columns=columns)

In [45]:
df0.head()

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

#### OR

In [46]:
datajson = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [47]:
df = pd.DataFrame(datajson)

In [48]:
df.head()

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               5 non-null      object 
 1   Model              5 non-null      object 
 2   Year               5 non-null      int64  
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64  
 5   Transmission Type  5 non-null      object 
 6   Vehicle_Style      5 non-null      object 
 7   MSRP               5 non-null      int64  
dtypes: float64(1), int64(3), object(4)
memory usage: 452.0+ bytes


### Series

In [50]:
df.Model

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: object

In [51]:
df['Model']

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: object

In [52]:
df[['Make', "Model", "MSRP"]]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [53]:
df['id'] = [1,2,3,4,5]

In [54]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [55]:
del df["id"]

In [56]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [57]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [58]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [59]:
df.loc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [60]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [61]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [62]:
df.iloc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [63]:
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

### Operation

In [64]:
df["Engine HP"]/10

a    13.8
b     NaN
c    21.8
d    19.4
e    26.1
Name: Engine HP, dtype: float64

In [65]:
df["Year"] > 2015

a    False
b     True
c    False
d     True
e     True
Name: Year, dtype: bool

In [66]:
df[df["Year"] > 2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
d       4dr SUV  34450  
e        Pickup  32340

### String operations

In [67]:
df["Vehicle_Style"]

a          sedan
b          Sedan
c    convertible
d        4dr SUV
e         Pickup
Name: Vehicle_Style, dtype: object

In [68]:
df["Vehicle_Style"].str.lower()

a          sedan
b          sedan
c    convertible
d        4dr suv
e         pickup
Name: Vehicle_Style, dtype: object

In [69]:
df["Vehicle_Style"].str.replace(" ", "_")

a          sedan
b          Sedan
c    convertible
d        4dr_SUV
e         Pickup
Name: Vehicle_Style, dtype: object

### Summary

In [70]:
df.MSRP.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, a to e
Series name: MSRP
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 252.0+ bytes


In [71]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [72]:
df.MSRP.mean()

30186.0

In [73]:
df.Model.unique()

array(['Stanza', 'Sonata', 'Elise', 'Acadia', 'Frontier'], dtype=object)

In [74]:
df.isna()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
a  False  False  False      False             False              False   
b  False  False  False       True             False              False   
c  False  False  False      False             False              False   
d  False  False  False      False             False              False   
e  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
a          False  False  
b          False  False  
c          False  False  
d          False  False  
e          False  False

In [75]:
df.isnull() == df.isna()

Make  Model  Year  Engine HP  Engine Cylinders  Transmission Type  \
a  True   True  True       True              True               True   
b  True   True  True       True              True               True   
c  True   True  True       True              True               True   
d  True   True  True       True              True               True   
e  True   True  True       True              True               True   

   Vehicle_Style  MSRP  
a           True  True  
b           True  True  
c           True  True  
d           True  True  
e           True  True

In [76]:
df.isna().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

### Grouping
```
SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
```

In [77]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [78]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340], dtype=int64)

In [79]:
df.to_dict()

{'Make': {'a': 'Nissan',
  'b': 'Hyundai',
  'c': 'Lotus',
  'd': 'GMC',
  'e': 'Nissan'},
 'Model': {'a': 'Stanza',
  'b': 'Sonata',
  'c': 'Elise',
  'd': 'Acadia',
  'e': 'Frontier'},
 'Year': {'a': 1991, 'b': 2017, 'c': 2010, 'd': 2017, 'e': 2017},
 'Engine HP': {'a': 138.0, 'b': nan, 'c': 218.0, 'd': 194.0, 'e': 261.0},
 'Engine Cylinders': {'a': 4, 'b': 4, 'c': 4, 'd': 4, 'e': 6},
 'Transmission Type': {'a': 'MANUAL',
  'b': 'AUTOMATIC',
  'c': 'MANUAL',
  'd': 'AUTOMATIC',
  'e': 'MANUAL'},
 'Vehicle_Style': {'a': 'sedan',
  'b': 'Sedan',
  'c': 'convertible',
  'd': '4dr SUV',
  'e': 'Pickup'},
 'MSRP': {'a': 2000, 'b': 27150, 'c': 54990, 'd': 34450, 'e': 32340}}

In [80]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]